name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.10
        cache: "pip"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 coverage

    - name: Check PEP 8 Compliance
      run: flake8 --statistics .

    - name: Run Unit Tests
      run: pytest

    - name: Check Test Coverage
      run: coverage run -m pytest
    - name: Check Coverage Percentage
      run: coverage report --fail-under=90

    - name: Check Docstrings
      run: pydocstyle .
