name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'
    
    - name: Set up pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - name: Debug
      run: |
        ls -la
        ls -la /github/workspace

    - name: Install Requirements Dependencies
      run: |
        REQ_FILE=$(find /github/workspace -name "requirements.txt")
        if [ -f "$REQ_FILE" ]; then
            pip install -r "$REQ_FILE"
        else
            echo "requirements.txt not found"
        fi

    - name: Install PEP8 Dependencies
      run: |
        pip install flake8 coverage

    - name: Check PEP 8 Compliance
      run: flake8 --statistics .

    - name: Run Unit Tests
      run: pytest

    - name: Check Test Coverage
      run: coverage run -m pytest
    - name: Check Coverage Percentage
      run: coverage report --fail-under=90

    - name: Check Docstrings
      run: pydocstyle .
